application: matarvefur
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /_ah/spi/.*
  script: api.api

- url: /js
  static_dir: static/js

- url: /img
  static_dir: static/img

- url: /fonts
  static_dir: static/fonts

- url: /bootstrap
  static_dir: static/bootstrap

- url: /
  static_files: templates/index.html
  upload: templates/index\.html
  secure: always
  
- url: /(20\d\d-(01|02|03|04|05|06|07|08|09|1|2|3|4|5|6|7|8|9|10|11|12)?-((0|1|2)?\d|30|31))$
  static_files: templates/skra.html
  upload: templates/skra\.html
  secure: always

libraries:
- name: webapp2
  version: "2.5.2"

- name: endpoints
  version: latest